telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "your-webhook-path"
  bot-name: "@your-bot"
  bot-token: "bot-token"

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: pg
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

server:
  port: 8443 # or 80, 88, 443
  ssl:
    enabled: true
    key-store: /path/to/keystore # see more there https://stackoverflow.com/questions/36991562/how-can-i-set-up-a-letsencrypt-ssl-certificate-and-use-it-in-a-spring-boot-appli
    key-store-password:
    key-store-type: PKCS12
    key-alias: tomcat